In [21]:
dataset = np.array([(1,7.3),(2,12.8),(3,16.8),(4,22.1),(5,27.9),(6,31.4),(7,36.8),(8,43.1)])
dataset2= [(1,2,3,4,5,6,7,8),(7.3,12.8,16.8,22.1,27.9,31.4,36.8,43.1)]

In [2]:
import numpy as np

In [8]:
C = np.cov(dataset2)

In [9]:
C

array([[  6.        ,  30.01428571],
       [ 30.01428571, 150.51357143]])

In [11]:
np.linalg.eig(C)

EigResult(eigenvalues=array([1.42114424e-02, 1.56499360e+02]), eigenvectors=array([[-0.98068778, -0.19557986],
       [ 0.19557986, -0.98068778]]))

In [18]:
l1 = 1.42114424e-02 # 0.0142...
l2 = 1.56499360e+02 #156.49...

v1 = (-0.98, -0.19)
v2 = np.array((0.19,-0.98))

In [22]:
y=np.array((7.3,12.8,16.8,22.1,27.9,31.4,36.8,43.1))
dataset

array([[ 1. ,  7.3],
       [ 2. , 12.8],
       [ 3. , 16.8],
       [ 4. , 22.1],
       [ 5. , 27.9],
       [ 6. , 31.4],
       [ 7. , 36.8],
       [ 8. , 43.1]])

In [32]:
dataset.shape
v2.shape

D1 = np.matmul(dataset,v2)
D1

array([ -6.964, -12.164, -15.894, -20.898, -26.392, -29.632, -34.734,
       -40.718])