# Teste de PCA com `crosstab` de países tranposta

In [50]:
import pandas as pd
from sklearn.decomposition import PCA
import numpy as np

In [4]:
df = pd.read_csv("/home/vortex/Documents/Fatec/Trabalhos/Projeto Integrador local/BD/Scripts/ANTAQ/Exportação por país/exp_pais_2018.csv")

In [5]:
df

Mercadoria          AE  \
0                     Cavalos, asininos e muares, vivos     0.00100   
1                       Animais vivos da espécie bovina     0.00200   
2            Animais vivos das espécies ovina e caprina     0.00100   
3                                  Outros animais vivos     0.00100   
4     Carnes de animais da espécie bovina, frescas o...     0.95988   
...                                                 ...         ...   
1106                  Antiguidades com mais de 100 anos     0.00100   
1107                             Bagagem desacompanhada     0.01128   
1108                                   Mala Diplomática     0.00725   
1109  Consumo de bordo (exceto combustíveis e lubrif...    69.31955   
1110                                              Total  1424.61316   

             AG         AN         AO           AR        AU        AW  \
0      0.000000   0.000000    0.00100     1.213100  0.001000  0.000000   
1      0.002000   0.002000    0.00000     0.002000  0.002000  0.002000   
2      0.000000   0.000000    0.00100     0.001000  0.001000  0.000000   
3      0.000000   0.000000    0.00100     0.011480  0.001000  0.000000   
4      0.000000   0.000000    0.00100     0.604930  0.001000  0.000000   
...         ...        ...        ...          ...       ...       ...   
1106   0.000000   0.000000    0.00100     0.001000  0.001000  0.000000   
1107   0.000000   0.000000    0.03921     0.302300  0.001000  0.000000   
1108   0.000000   0.000000    0.00100     0.006470  0.001000  0.000000   
1109   0.000000   0.000000   52.56091   209.217340  0.001000  0.000000   
1110  11.150728  15.140103  223.66055  1456.883986  4.636202  0.199169   

               BD           BE  ...          TW       UA           US  \
0        0.001000     0.001000  ...    0.001000  0.00100     0.001000   
1        0.002000     0.002000  ...    0.002000  0.00000     0.002000   
2        0.001000     0.001000  ...    0.001000  0.00100     0.001000   
3        0.001000     0.001000  ...    0.001000  0.00100     0.001000   
4        0.001000     0.040070  ...    0.001000  0.00100     0.046550   
...           ...          ...  ...         ...      ...          ...   
1106     0.001000     0.001000  ...    0.001000  0.00100     0.001000   
1107     0.001000     0.174980  ...    0.001000  0.00100     1.239020   
1108     0.001000     0.004190  ...    0.001000  0.00100     0.042070   
1109     0.001000   137.352490  ...    0.001000  0.00100   583.500040   
1110  2032.678422  1348.797092  ...  683.596168  1.29436  3452.320054   

              UY         VE         VI           VN         YE          ZA  \
0       0.151540    0.00100   0.000000     0.001000    0.00000    0.001000   
1       0.002000    0.00200   0.002000     0.002000    0.00200    0.002000   
2       0.001000    0.00100   0.000000     0.001000    0.00000    0.001000   
3       0.001000    0.00100   0.000000     0.001000    0.00000    0.001000   
4       0.030970    0.00100   0.000000     0.001000    0.00000    0.011390   
...          ...        ...        ...          ...        ...         ...   
1106    0.003350    0.00100   0.000000     0.001000    0.00000    0.001000   
1107    0.120580    0.00100   0.000000     0.001000    0.00000    0.179100   
1108    0.001000    0.00100   0.000000     0.001000    0.00000    0.003810   
1109   30.313500    0.00100   0.000000    26.508220    0.00000  145.039680   
1110  188.694298  100.05599  31.258143  3025.393854  177.72368  581.592542   

             Total  
0         1.466640  
1         5.285290  
2         0.129600  
3         0.114480  
4        37.554950  
...            ...  
1106      0.106350  
1107      4.152130  
1108      0.204230  
1109   4977.102090  
1110  66919.425256  

[1111 rows x 116 columns]

In [162]:
pca = PCA(n_components=3)

In [163]:
df_T = df.drop("Mercadoria", axis=1).T
df_teste = df.drop("Mercadoria", axis=1)

In [164]:
pca.fit(df_T)

PCA(n_components=3)

In [170]:
v_lista = pca.components_
v_lista

array([[ 1.33789571e-06,  1.33789571e-06,  1.33789571e-06, ...,
         1.65924680e-01,  2.45644815e-01,  9.33367243e-01],
       [-4.00636460e-01, -1.63236479e-01, -1.38896581e-01, ...,
         2.12896941e-03,  9.64269609e-02,  8.69317345e-01],
       [-3.73845585e-01, -2.03097456e-01, -1.63247151e-01, ...,
         4.67728316e-05,  2.47401753e-01,  8.41759734e-01]])

In [166]:
eigen_val = pca.explained_variance_
eigen_val

array([47451456.51388906,   835390.5189449 ,   157477.14514606])

In [167]:
v_lista

array([[ 1.90103805e-05,  6.75114468e-05,  1.66710793e-06, ...,
         2.65162216e-06,  6.52492695e-02,  9.33367243e-01],
       [-3.45260879e-05, -1.12623342e-04, -2.86057790e-06, ...,
        -4.79472407e-06, -1.13534133e-01, -1.12108772e-01],
       [-4.51513278e-05, -1.21577952e-04, -3.08698451e-06, ...,
        -6.59638157e-06, -1.63247151e-01, -1.15307152e-01]])

In [168]:
v_lista.sort()
v_lista

array([[ 1.33789571e-06,  1.33789571e-06,  1.33789571e-06, ...,
         1.65924680e-01,  2.45644815e-01,  9.33367243e-01],
       [-4.00636460e-01, -1.63236479e-01, -1.38896581e-01, ...,
         2.12896941e-03,  9.64269609e-02,  8.69317345e-01],
       [-3.73845585e-01, -2.03097456e-01, -1.63247151e-01, ...,
         4.67728316e-05,  2.47401753e-01,  8.41759734e-01]])

In [169]:
pca.get_feature_names_out()

array(['pca0', 'pca1', 'pca2'], dtype=object)

In [203]:
f_transformado = pca.fit_transform(df_T)
f_df = pd.DataFrame(f_transformado)
f_df = f_df.T
f_df.index = df["Mercadoria"][0:3]

In [204]:
f_df

0            1    \
Mercadoria                                                            
Cavalos, asininos e muares, vivos           315.627743 -1229.344833   
Animais vivos da espécie bovina            -277.609802    34.193853   
Animais vivos das espécies ovina e caprina -620.036840     1.882044   

                                                    2            3    \
Mercadoria                                                             
Cavalos, asininos e muares, vivos          -1227.355817 -1008.781639   
Animais vivos da espécie bovina               35.390448   -14.321834   
Animais vivos das espécies ovina e caprina     5.287495   -73.208063   

                                                   4            5    \
Mercadoria                                                            
Cavalos, asininos e muares, vivos           141.649169 -1237.176050   
Animais vivos da espécie bovina            -170.137985    36.605700   
Animais vivos das espécies ovina e caprina -169.557009     6.542815   

                                                    6           7    \
Mercadoria                                                            
Cavalos, asininos e muares, vivos          -1241.377938  996.232960   
Animais vivos da espécie bovina               37.213683 -648.555935   
Animais vivos das espécies ovina e caprina     7.249100    0.929966   

                                                   8            9    ...  \
Mercadoria                                                           ...   
Cavalos, asininos e muares, vivos            53.522768 -1240.411430  ...   
Animais vivos da espécie bovina            -166.480417    37.095893  ...   
Animais vivos das espécies ovina e caprina -244.831778     7.127017  ...   

                                                   105          106  \
Mercadoria                                                            
Cavalos, asininos e muares, vivos          -484.396460 -1240.356294   
Animais vivos da espécie bovina             -79.696298    37.090417   
Animais vivos das espécies ovina e caprina  296.470876     7.122001   

                                                    107          108  \
Mercadoria                                                             
Cavalos, asininos e muares, vivos           2067.046881 -1063.269973   
Animais vivos da espécie bovina             -479.398644    12.417687   
Animais vivos das espécies ovina e caprina  -597.616726   -19.865855   

                                                    109          110  \
Mercadoria                                                             
Cavalos, asininos e muares, vivos          -1132.006333 -1212.228876   
Animais vivos da espécie bovina               10.019897    33.423368   
Animais vivos das espécies ovina e caprina   -40.905179     3.170995   

                                                    111          112  \
Mercadoria                                                             
Cavalos, asininos e muares, vivos           2044.658612 -1046.389232   
Animais vivos da espécie bovina            -1296.063903   -11.671218   
Animais vivos das espécies ovina e caprina  1640.608015   -79.597571   

                                                   113           114  
Mercadoria                                                            
Cavalos, asininos e muares, vivos          -667.001199  70148.445686  
Animais vivos da espécie bovina             -71.511850  -2103.820709  
Animais vivos das espécies ovina e caprina -100.361630   -410.843138  

[3 rows x 115 columns]

## Teste

In [258]:
dataset_sk_arr = np.array([(1,7.3),(2,12.8),(3,16.8),(4,22.1),(5,27.9),(6,31.4),(7,36.8),(8,43.1)])

In [259]:
dt_temp1 = dataset_sk_arr[:, 0].copy()
dataset_sk_arr[:, 0] = dataset_sk_arr[:, 1]
dataset_sk_arr[:, 1] = dt_temp1
dataset_sk_arr

array([[ 7.3,  1. ],
       [12.8,  2. ],
       [16.8,  3. ],
       [22.1,  4. ],
       [27.9,  5. ],
       [31.4,  6. ],
       [36.8,  7. ],
       [43.1,  8. ]])

In [260]:
pca_x = PCA(n_components=1)

In [261]:
pca_x.fit(dataset_sk_arr)

PCA(n_components=1)

In [262]:
pca_x.components_

array([[0.98068778, 0.19557986]])

In [263]:
pca_x.explained_variance_

array([156.49935999])

In [264]:
modelo = pca_x.transform(dataset_sk_arr)

In [265]:
modelo

array([[-17.82204843],
       [-12.23268579],
       [ -8.11435482],
       [ -2.72112974],
       [  3.16243924],
       [  6.79042632],
       [ 12.28172018],
       [ 18.65563305]])